version: 2
updates:
  - package-ecosystem: maven
    directory: /
    target-branch: development
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    target-branch: development
    schedule:
      interval: monthly
